INSERT INTO job_title (name) VALUES ('Диспетчер');
INSERT INTO job_title (name) VALUES ('Администратор');
INSERT INTO job_title (name) VALUES ('Пилот');
INSERT INTO job_title (name) VALUES ('Штурман');
INSERT INTO job_title (name) VALUES ('Радист');
INSERT INTO job_title (name) VALUES ('Стюардесса');
INSERT INTO state (name) VALUES ('регистрация');
INSERT INTO state (name) VALUES ('посадка');
INSERT INTO state (name) VALUES ('посадка закончена');
INSERT INTO state (name) VALUES ('вылетел');
INSERT INTO state (name) VALUES ('отменен');
INSERT INTO state (name) VALUES ('задержан');
INSERT INTO state (name, need_date_time) VALUES ('ожидается в', true);
INSERT INTO state (name, need_date_time) VALUES ('совершил посадку в', true);